yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group_post/', views.group_posts, name='group_posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_update'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Content')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    db_index=True,
                                    verbose_name='date'
                                    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following')

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст Вашего поста',
            'group': 'Группа',
            'image': 'Картинка к Вашему посту'
        }
        help_texts = {
            'text': 'Текст поста',
            'group': 'Группа, к которой относится пост!',
            'image': 'Картинка к Вашему посту'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Текст Вашего комментария',
        }

yatube/posts/views.py
from http.client import HTTPResponse

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User

NUMBER_OF_POSTS = 10


def paginator_func(request, posts):
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@require_GET
def index(request):
    posts = Post.objects.select_related('author', 'group')
    text_main = 'Последние обновления на сайте'
    template = 'posts/index.html'
    keyword = request.GET.get("q", None)
    if keyword:
        posts = Post.objects.select_related('author', 'group').filter(
            text__icontains=keyword)
        if posts:
            text_main = 'Найдено:'
            posts = Post.objects.select_related('author', 'group').filter(
                text__icontains=keyword)
        else:
            text_main = 'По Вашему запросу ничего не найдено'
    context = {
        'text_main': text_main,
        'page_obj': paginator_func(request, posts),
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    text_groups = f'Записи сообщества "{group.title}"'
    posts = group.posts.select_related('author', 'group')
    context = {
        'text_groups': text_groups,
        'group': group,
        'page_obj': paginator_func(request, posts),
    }
    return render(request, template, context)


def profile(request, username):
    author_name = get_object_or_404(User, username=username)
    if author_name:
        posts = Post.objects.select_related('author',
                                            'group').filter(author=author_name)
        all_author_posts = author_name.posts.count()
        if (request.user.is_authenticated
            and Follow.objects.filter(user=request.user,
                                      author=author_name).exists()):
            following = True
        else:
            following = False
        context = {
            'author_name': author_name,
            'all_author_posts': all_author_posts,
            'page_obj': paginator_func(request, posts),
            'following': following
        }
        return render(request, 'posts/profile.html', context)
    return HTTPResponse('Ничего не найдено по запросу о данном авторе.')


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related(), pk=post_id)
    all_author_posts = post.author.posts.count()
    title_30 = post.text[:30]
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'all_author_posts': all_author_posts,
        'title_30': title_30,
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form,
                                                          'is_edit': False})
    new_post = form.save(commit=False)
    new_post.author_id = request.user.id
    new_post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    is_edit = True
    if request.user.username != post.author.username:
        return redirect(f'/profile/{post.author.username}/')
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    if request.method != 'POST':
        context = {
            'form': form,
            'post': post,
            'is_edit': is_edit
        }
        return render(
            request,
            'posts/create_post.html',
            context
        )
    form = PostForm(request.POST, instance=post, files=request.FILES or None,)
    if not form.is_valid():
        context = {
            'form': form,
            'post': post,
            'is_edit': is_edit
        }
        return render(request, 'posts/create_post.html', context)
    form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comment = Comment.objects.filter(post=post)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follow_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_func(request, follow_list)
    follow = True
    context = {'follow': follow,
               'page_obj': page_obj
               }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if (request.user != author
            and not Follow.objects.filter(user=request.user,
                                          author=author).exists()):
        Follow.objects.create(user=request.user,
                              author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user,
                             author=author):
        Follow.objects.filter(user=request.user,
                              author=author).delete()
    return redirect('posts:profile', author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% if is_edit %}
      <h1>Редактировать пост</h1>
      {% url 'posts:post_update' post.id as the_url %}
      {% include 'includes/form.html' with card_title='Редактировать пост' action_url=the_url button_text='Сохранить' %}
    {% else %}
      <h1>Новый пост</h1>
      {% url 'posts:post_create' as the_url %}
      {% include 'includes/form.html' with card_title='Новый пост' action_url=the_url button_text='Добавить' %}
    {% endif %}
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}  
{% block title %}
  Ваши подписки
{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="container py-1">
    <h1>Ваши подписки</h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/publication_card.html'%}
    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% block title %}{{text_groups}} {{ group }}{% endblock %}
  {% block content %}
  <div class="container py-5">
    <h1>
      {{ group }}
    </h1>
    <p> 
      {{ group.description }} 
    </p>
    {%for post in page_obj%}
      {% include 'includes/publication_card.html' %}
      {% if not forloop.last %}
        <hr>
      {%endif%}
    {% endfor %}
    {% include 'includes/paginator.html' %}       
  </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
<title>{% block title %}{{text_main}}{% endblock %}</title>
{% block content %}
  <div class="container">
    <h1>Поиск по записям</h1>
    <div class="card">
      <div class="card-body">
        <form class="form-inline" action="/">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          <div class="form-row">
          <input name="q" class="form-control form-control-lg" type="search" 
            placeholder="Поиск" 
              {% if keyword %}
                  value="{{ keyword }}"
              {% endif %}
          >
          <button class="btn" type="submit">Найти</button>
          </div>
        </form>
        </div>
      </div>
    </div>
  <div class="container py-5">     
    <h1>{{text_main}}</h1>
    {% include 'includes/switcher.html'%}
    {% for post in page_obj %}
      {% include 'includes/publication_card.html' %}
      {% if not forloop.last %}<hr>{%endif%}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>  
{% endblock %}
</body>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ title_30 }}{% endblock %}
{%block content%}
    <div class="container py-5">
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}
                    <li class="list-group-item">
                        Группа: {{ post.group.title }}
                        <br>
                        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                    </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{post.author.get_full_name}}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора:  <span >{{all_author_posts}}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author.username %}">
                    все посты пользователя
                    </a>
                </li>
                </ul>
            </aside>
        <article class="col-12 col-md-9">
            <h1>Пост {{ title_30 }}</h1>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ post.text|linebreaksbr }}
            </p>
            {% if user.is_authenticated %}
                {% url 'posts:add_comment' post.id as the_url %}
                {% include 'includes/form.html' with card_title='Добавить комментарий' action_url=the_url button_text='Добавить' %}
            {% endif %}
            {% include 'includes/comments.html' %}
        </article> 
    </div>
{%endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{author_name}}{% endblock %}
{%block content%}
  <div class="container py-5">    
    <div class="mb-5">    
      <h1>
        Все посты пользователя {{author_name}}
      </h1>
      <h3>
        Всего постов: {{all_author_posts}}
      </h3>
      {% if request.user.is_authenticated and request.user != author %}
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author_name.username %}" role="button"
        >
          Отписаться
        </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author_name.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    {% endif %}   
      {% for post in page_obj %}
        {% include 'includes/publication_card.html' %}
      {%endfor%}
      {% include 'includes/paginator.html' %}
    </div>
  </div>
{%endblock%}